spring:
  application:
    name: fasteam-backend

  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:fasteam}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_SECRET:40ee7ff1ac402e978697b6509829eab58c1274c4376337c89a5590c157a0f1202ed6a73c89d7fedcb8d6b5ca08ded7073e266a3af483997b0a0a46c5bd4cb8d4}
  expiration: ${JWT_EXPIRATION:3600000}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION:604800000}

server:
  port: ${SERVER_PORT:8080}
